
# html lang
language: zh-CN

# 菜单
menu:
  - label: 首页
    url: /
    route: /
  - label: 分类
    url: /categories
    route: /categories/
  - label: 归档
    url: /archives
    route: /archives/
  - label: 朋友圈
    url: /friends
    route: /friends/

# stylesheets loaded in the <head>
stylesheets:
- /iconfont/iconfont.css
- /css/mcolor.css
- /prism/prism.css

# scripts loaded in the end of the body
scripts:
- /js/mcolor.js
- /js/search.js
- /prism/prism.js
- //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# atom
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true
  template:

# 头像
avatar: /images/avatar.jpeg

# 昵称
nickname: ITSATAN

# 签名
signature: (路漫漫其修远兮，吾将上下而求索)

# 最新文章
article_enable: false

# 我的标签
tags_enable: true

# 工具栏
tool_enable: false

# 广告位
ads:
  enable: false
  ad:
    - picture: 图片路径
      desc: 图片描述
      link: 图片地址

# 广播频道
broadcast:
  enable: false
  record:
    - text: 记录我的坎坷经历～

# 朋友圈
friends:
- avatar: /images/avatar.jpeg
  name: ITSATAN
  desc: 路漫漫其修远兮，吾将上下而求索
  link: https://github.com/itsatan

# 不蒜子统计
busuanzi:
  enable: true

# 版权信息
copyright:
  enable: true
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'